# See: http://about.travis-ci.org/docs/user/build-configuration/

language: php
php:
  - 5.6

install:
    - composer self-update
    - composer install --dev -vv

script:
    - phpunit -c phpunit.xml.dist

notifications:
    on_success: always
    on_failure: always