# See: http://about.travis-ci.org/docs/user/build-configuration/

language: php
php:
  - 5.3

before_script:
    - php composer.phar install --dev -vv
script:
    - phpunit -c phpunit.xml.dist

notifications:
  on_success: always
  on_failure: always